---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmrs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/veerendradevops/argocd-k8s.git
    targetRevision: main
    path: openmrs
  destination:
    server: https://kubernetes.default.svc
    namespace: openmrs
  syncPolicy:
    automated:
      selfHeal: true
      allowEmpty: true
      prune: true

###Target revision is branch name ###
